language: php

php:
  - 5.3
  - 5.4
  - 5.5
  - hhvm

before_script:
  - composer self-update
  - composer install --no-interaction --prefer-source --dev

script:
  - mkdir -p build/logs
  - phpunit --coverage-clover build/logs/clover.xml

after_script:
  - vendor/bin/phpunit --verbose --coverage-clover=coverage.clover
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover coverage.clover

matrix:
  allow_failures:
    - php: hhvm
  fast_finish: true